version: "3.3"

services:
    database:
        restart: always
        container_name: postgres
        image: postgres
        volumes:
            - ./database/data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=spring-boot-crud
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_PORT=5432
        ports:
            - "5432:5432"
